/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoapo;

/**
 *
 * @author Mateo Salcedo
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();

        jCheckBox1.setBackground(new java.awt.Color(255, 102, 102));
        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 102, 102));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 204));
        jMenuBar1.setOpaque(true);

        jMenu1.setBackground(new java.awt.Color(255, 255, 204));
        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\OneDrive\\Escritorio\\dadad.png")); // NOI18N
        jMenu1.setText("Granja");
        jMenu1.setContentAreaFilled(false);
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenu1.setOpaque(true);

        jMenuItem1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\vaca.png")); // NOI18N
        jMenuItem1.setText("Vaca");
        jMenuItem1.setOpaque(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(255, 204, 204));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\cerdo.png")); // NOI18N
        jMenuItem2.setText("Cerdo");
        jMenuItem2.setOpaque(true);
        jMenu1.add(jMenuItem2);

        jMenuItem3.setBackground(new java.awt.Color(255, 204, 153));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\caballo.png")); // NOI18N
        jMenuItem3.setText("Caballo");
        jMenuItem3.setOpaque(true);
        jMenu1.add(jMenuItem3);

        jMenuItem4.setBackground(new java.awt.Color(255, 153, 102));
        jMenuItem4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\gallina.png")); // NOI18N
        jMenuItem4.setText("Gallina");
        jMenuItem4.setOpaque(true);
        jMenu1.add(jMenuItem4);

        jMenuItem5.setBackground(new java.awt.Color(204, 255, 255));
        jMenuItem5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\perro.png")); // NOI18N
        jMenuItem5.setText("Perro");
        jMenuItem5.setOpaque(true);
        jMenu1.add(jMenuItem5);

        jMenuItem6.setBackground(new java.awt.Color(255, 198, 243));
        jMenuItem6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\oveja.png")); // NOI18N
        jMenuItem6.setText("Oveja");
        jMenuItem6.setOpaque(true);
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\conejo.png")); // NOI18N
        jMenuItem7.setText("Conejo");
        jMenu1.add(jMenuItem7);

        jCheckBoxMenuItem4.setBackground(new java.awt.Color(204, 255, 204));
        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("Pato");
        jCheckBoxMenuItem4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\pato.png")); // NOI18N
        jCheckBoxMenuItem4.setOpaque(true);
        jMenu1.add(jCheckBoxMenuItem4);

        jCheckBoxMenuItem3.setBackground(new java.awt.Color(255, 204, 153));
        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Burro");
        jCheckBoxMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\burro.png")); // NOI18N
        jCheckBoxMenuItem3.setOpaque(true);
        jMenu1.add(jCheckBoxMenuItem3);

        jMenu3.setBackground(new java.awt.Color(255, 218, 145));
        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\saco-de-trigo.png")); // NOI18N
        jMenu3.setText("Comida para animales");
        jMenu3.setOpaque(true);

        jMenuItem8.setBackground(new java.awt.Color(153, 255, 153));
        jMenuItem8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\cesped.png")); // NOI18N
        jMenuItem8.setText("Hierba");
        jMenuItem8.setToolTipText("");
        jMenuItem8.setOpaque(true);
        jMenu3.add(jMenuItem8);

        jMenuItem9.setBackground(new java.awt.Color(255, 255, 204));
        jMenuItem9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\heno.png")); // NOI18N
        jMenuItem9.setText("Heno");
        jMenuItem9.setOpaque(true);
        jMenu3.add(jMenuItem9);

        jMenuItem10.setBackground(new java.awt.Color(204, 255, 153));
        jMenuItem10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\maiz.png")); // NOI18N
        jMenuItem10.setText("Maiz");
        jMenuItem10.setOpaque(true);
        jMenu3.add(jMenuItem10);

        jMenuItem11.setBackground(new java.awt.Color(255, 204, 153));
        jMenuItem11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\zanahoria.png")); // NOI18N
        jMenuItem11.setText("Zanahoria");
        jMenuItem11.setOpaque(true);
        jMenu3.add(jMenuItem11);

        jMenuItem12.setBackground(new java.awt.Color(204, 153, 255));
        jMenuItem12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\bocadillo.png")); // NOI18N
        jMenuItem12.setText("Concentrado");
        jMenuItem12.setOpaque(true);
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem13.setBackground(new java.awt.Color(243, 243, 208));
        jMenuItem13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\cebada.png")); // NOI18N
        jMenuItem13.setText("Cebada");
        jMenuItem13.setOpaque(true);
        jMenu3.add(jMenuItem13);

        jMenuItem14.setBackground(new java.awt.Color(255, 181, 145));
        jMenuItem14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\papa.png")); // NOI18N
        jMenuItem14.setText("Tuberculos");
        jMenuItem14.setOpaque(true);
        jMenu3.add(jMenuItem14);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 204));
        jMenu2.setText("Opciones");
        jMenu2.setToolTipText("");
        jMenu2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenu2.setOpaque(true);

        jMenuItem15.setBackground(new java.awt.Color(255, 204, 204));
        jMenuItem15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Salcedo\\Downloads\\cerrar.png")); // NOI18N
        jMenuItem15.setText("Cerrar");
        jMenuItem15.setOpaque(true);
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
